name: Deploy to Oracle VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: 'Create env file'
      run: |
        touch .env
        echo API_KEY_GITHUB=${{ secrets.API_KEY_GITHUB }} >> .env
        echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
        echo NEXT_PUBLIC_GITHUB_USERNAME=${{ secrets.NEXT_PUBLIC_GITHUB_USERNAME }} >> .env
        cat .env
    
    - name: Build project
      env:
        API_KEY_GITHUB: ${{ secrets.API_KEY_GITHUB }}
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_GITHUB_USERNAME: ${{ secrets.NEXT_PUBLIC_GITHUB_USERNAME }}
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code on VPS and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd vscode-portfolio
          git pull origin main
          
          # Create .env file on VPS
          rm -f .env
          touch .env
          echo API_KEY_GITHUB=${{ secrets.API_KEY_GITHUB }} >> .env
          echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
          echo NEXT_PUBLIC_GITHUB_USERNAME=${{ secrets.NEXT_PUBLIC_GITHUB_USERNAME }} >> .env
          cat .env
          
          npm install
          pm2 reload all

  restart:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Ensure PM2 process restart
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd vscode-portfolio
          pm2 restart all